ivi-layermanagement-api/ilmControl/src/ilm_control_wayland_platform.c

I found some memory leaks in libilmControl.so while I am testing it with valgrind

Memleak fixes for ilmControl

---

CMakeLists.txt

This release:
- fixes several memory leaks
- introduces touch support for subsurfaces
- introduces two new subcmd to LayerManagerControl

Bump version to 1.11.0 stable release

---

ivi-layermanagement-api/ilmControl/include/ilm_control.h

correction of the obvious copy-paste error in the comments

ilmControl: update comments for ilm_[un]registeNotification apis

---

ivi-input-api/test/CMakeLists.txt
ivi-input-api/test/TestBase.cpp
ivi-input-api/test/TestBase.h
ivi-input-api/test/ilm_input_null_pointer_test.cpp
ivi-input-api/test/ilm_input_test.cpp
ivi-layermanagement-api/test/CMakeLists.txt
ivi-layermanagement-api/test/TestBase.cpp
ivi-layermanagement-api/test/TestBase.h
ivi-layermanagement-api/test/ilm_control_notification_test.cpp
ivi-layermanagement-api/test/ilm_control_test.cpp

This PR removes all previously deprecated APIs from tests

Remove deprecated ap is from tests v1

---

ivi-input-modules/ivi-input-controller/src/ivi-input-controller.c
protocol/CMakeLists.txt
weston-ivi-shell/CMakeLists.txt
weston-ivi-shell/src/ivi-controller.c
weston-ivi-shell/src/ivi-share-gbm.c
weston-ivi-shell/src/ivi-share.h

This branch updates wayland-ivi-extension to work with weston 2.0

Update to weston 2.0

---

ivi-layermanagement-api/ilmCommon/include/ilm_types.h
ivi-layermanagement-api/ilmControl/include/ilm_control.h
ivi-layermanagement-api/ilmControl/include/ilm_control_platform.h
ivi-layermanagement-api/ilmControl/src/ilm_control_wayland_platform.c
ivi-layermanagement-api/test/ilm_control_test.cpp
ivi-layermanagement-examples/LayerManagerControl/src/commands.cpp
protocol/CMakeLists.txt
protocol/ivi-wm.xml
weston-ivi-shell/src/ivi-controller.c

I removed the layer and surface interfaces. I rename the protocol as ivi-wm.xml. WM means Window Manager. I renamed the surface_configuration event as surface_size event, and put some more information about the event.

Ivi wm protocol v3

---

ivi-layermanagement-api/ilmCommon/include/ilm_types.h
ivi-layermanagement-api/ilmControl/src/ilm_control_wayland_platform.c
ivi-layermanagement-examples/LayerManagerControl/src/analyze.cpp
ivi-layermanagement-examples/LayerManagerControl/src/print.cpp
ivi-layermanagement-examples/LayerManagerControl/src/sceneio.cpp
protocol/ivi-wm.xml
weston-ivi-shell/src/ivi-controller.c

This is a nice debugging feature by @eucan. Compositor sends information about received number of frames from a surface.

Implement frame counter

---

ivi-input-modules/ivi-input-controller/src/ivi-input-controller.c

These changes resolve several bugs in ivi-input-controller. @HarshaMM  and @anilvalmiki

Ivi input controller bugfixes

---

ivi-layermanagement-examples/LayerManagerControl/src/commands.cpp
ivi-layermanagement-examples/LayerManagerControl/src/input_commands.cpp
ivi-layermanagement-examples/LayerManagerControl/src/print.cpp
ivi-layermanagement-examples/simple-ivi-share/src/simple-ivi-share.c

I fixed many memory leaks in LayerManagerControl and simple-ivi-share

Examples fix memleaks

---

ivi-layermanagement-examples/layer-add-surfaces/src/layer-add-surfaces.c

modifying the printf logs, making if a bit better from my point of view :-)

layer-add-surfaces: cosmetic modify print logs

---

README

Update this git repo URL

---

ivi-layermanagement-api/ilmControl/src/ilm_control_wayland_platform.c

Don't send notifications after every ivi_wm_get_layer/surface*
request. Track the changes and send notifications only
after something is changed

Dont send superfluous notifications

---

ivi-input-modules/ivi-input-controller/src/ivi-input-controller.c

It might happen that default seat does not exist.
Therefore, we have to check the existence of the seat,
before adding to accepted_seat_list of a surface.
When default seat is created later, we should add it
to accepted_seat_list of all surfaces.

ivi-input: don't add non-existing default seat

---

ivi-input-modules/ivi-input-controller/src/ivi-input-controller.c
ivi-layermanagement-api/ilmInput/src/ilm_input.c
ivi-layermanagement-examples/EGLWLInputEventExample/src/WLContext.cpp
ivi-layermanagement-examples/EGLWLInputEventExample/src/main.cpp
ivi-layermanagement-examples/EGLWLMockNavigation/src/OpenGLES2App.cpp
ivi-layermanagement-examples/LayerManagerControl/src/print.cpp
ivi-layermanagement-examples/simple-weston-client/src/simple-weston-client.c
weston-ivi-shell/src/ivi-controller.c

These patches are fixing the findings which I found out with clang source code analyzer

Fix source analyzer findings

---

README
ivi-input-modules/ivi-input-controller/src/ivi-input-controller.c
weston-ivi-shell/CMakeLists.txt
weston-ivi-shell/src/ivi-controller.c
weston-ivi-shell/src/ivi-controller.h

Update wayland-ivi-extension to use weston 4.0

Weston v4 adaptations

---

ivi-layermanagement-api/ilmCommon/include/ilm_common.h
ivi-layermanagement-api/ilmControl/include/ilm_control.h

- fix the ilmControl ilmClient section mismatch for doxygen
- define some ilm api in better wording
- fix the comment about the generation of the layer ids!

ivi-headers: correct the ilm header file comments

---

ivi-input-modules/ivi-input-controller/src/ivi-input-controller.c
weston-ivi-shell/src/ivi-controller.c

These patches fix invalid memory access during de-init of compositor.

Fix Invalid memory access during compositor deinit

---

ivi-input-modules/ivi-input-controller/CMakeLists.txt
ivi-input-modules/ivi-input-controller/src/ivi-input-controller.c
weston-ivi-shell/CMakeLists.txt
weston-ivi-shell/src/ivi-controller.c

This PR includes necessary changes to support Weston 5.0.

Update to use weston 5

---

ivi-layermanagement-examples/LayerManagerControl/src/Expression.cpp
ivi-layermanagement-examples/LayerManagerControl/src/ExpressionInterpreter.cpp

Added check to prevent conversion of filename into lowercase

LayerManagerControl: Prevent conversion of filenames into lowercase

---

protocol/ivi-application.xml

ivi-application: fix typo

---

ivi-id-agent-modules/ivi-id-agent/CMakeLists.txt
ivi-id-agent-modules/ivi-id-agent/src/ivi-id-agent.c
ivi-input-modules/ivi-input-controller/src/ivi-input-controller.c
ivi-layermanagement-examples/simple-weston-client/CMakeLists.txt

This PR includes necessary changes to support Weston 7.0.

Update to use Weston 7

---

ivi-id-agent-modules/ivi-id-agent/CMakeLists.txt
ivi-layermanagement-api/ilmControl/src/bitmap.c
ivi-layermanagement-examples/LayerManagerControl/src/sceneio.cpp
ivi-layermanagement-examples/simple-weston-client/CMakeLists.txt
weston-ivi-shell/src/ivi-controller.c

make the extension compatible with weston 8:
- update libweston in CMakeLists.txt
- fix crash in controller_screenshot_notify

Weston 8 compatible

---

ivi-layermanagement-api/ilmCommon/include/ilm_types.h
ivi-layermanagement-api/ilmControl/include/ilm_control.h
ivi-layermanagement-api/ilmControl/src/ilm_control_wayland_platform.c
ivi-layermanagement-api/test/ilm_control_notification_test.cpp

Maintain the idea of https://github.com/COVESA/wayland-ivi-extension/pull/129
Some improvements:
- Rename the new functions
- Typedef for define function pointer
- Fix the checking filename in callback
- Support non-blocking when filename is empty
- Create functional tests

Screenshot with callbacks

---

weston-ivi-shell/src/ivi-controller.c

ivi-controller: fix memory leak of background surface remove

ivi-controller: fix memory leak of background surface remove

---

ivi-input-modules/ivi-input-controller/src/ivi-input-controller.c

Weston introduces new structure, then it made some structures + API are modified.

ivi-input-controlelr: New struct weston_coord
