COVESA/wayland-ivi-extension

weston-ivi-shell/src/ivi-controller.c
When surface width is not multiple of 4, calculate padding for 24bit bmp image.
Signed-off-by: Wataru Mizuno <wmizuno@adit-jv.com>
=> ivi-controller: Correction ilm_takeScreenshot surface.

ivi-layermanagement-examples/LayerManagerControl/src/commands.cpp
for more testing from the command line.
=> LayerManagerControl: add two subcmd for add/remove a surface to/from a layer.

protocol/CMakeLists.txt
ivi-application is the new shared library which has the implementation
of ivi-application-protocol. The clients can use the library to create
ivi-surfaces.
=> ivi-application: introduce new helper library

ivi-layermanagement-examples/LayerManagerControl/src/commands.cpp
api's never worked and would even cause exception in LayerManagerControl tool
surface can only be created with native content and native content is
wayland-surface which is only available in the client.
So it does not make any sense to provide this functionality to external tool.
For surface destroy it is very similar issue, we can only destroy surfaces
which were created in the same client, but this is never the case by using
LayerManagerControl- every call will create new connection and therefore new client
=> LayerManagerControl: remove surface create and destroy api's

ivi-input-api/ilmInput/src/ilm_input.c, ivi-layermanagement-api/ilmClient/include/ilm_client.h, ivi-layermanagement-api/ilmClient/src/ilm_client.c, ivi-layermanagement-api/ilmCommon/include/ilm_types.h, ivi-layermanagement-api/ilmCommon/src/ilm_common.c, ivi-layermanagement-api/ilmControl/src/ilm_control_wayland_platform.c
it introduces new ILM_DEPRECATED macro and uses it to deprecate ilmClient APIs
=> Deprecate ilm client v2

ivi-layermanagement-api/ilmControl/include/ilm_control.h
A wayland compositor does not have any control over
the pixel format of the application surfaces.
Therefore, this API is deprecated.
=> ilmControl: mark surfaceGetPixelformat API as deprecated

weston-ivi-shell/src/ivi-share-gbm.c, weston-ivi-shell/src/ivi-share.c, weston-ivi-shell/src/ivi-share.h
The ivi-controller.so does not compile, if
ivi_share is activated. Because it includes
a non existing header file. The ivi-controller-interface
is renamed to ivi-layout-interface, and its contents
moved to ivi-layout-export.h
=> ivi-share: fix compilation issue

protocol/CMakeLists.txt
* libivi-application.so must be a link to
libivi-application.so.X.X.XX
* fix yocto package QA
Signed-off-by: Ronan Le Martret <ronan.lemartret@iot.bzh>
=> Fix ivi-application lib install

ivi-layermanagement-api/ilmControl/src/ilm_control_wayland_platform.c
Check ctx->wl.controller for not null.
If it is null, we cannot destroy any wayland objects.
The if statement is wrong.
=> ilmControl: fix memory leak at deinitialization

ivi-layermanagement-api/ilmControl/src/ilm_control_wayland_platform.c
Allocate memory in the size of accepted_seat struct instead of
size of a pointer of the struct
=> ilmControl: fix memory corruption at input listener

ivi-input-api/ilmInput/CMakeLists.txt, ivi-input-api/ilmInput/ilmInput.pc.in, ivi-layermanagement-api/ilmCommon/CMakeLists.txt, ivi-layermanagement-api/ilmCommon/ilmCommon.pc.in, ivi-layermanagement-api/ilmControl/CMakeLists.txt, ivi-layermanagement-api/ilmControl/ilmControl.pc.in, protocol/CMakeLists.txt, protocol/ivi-application.pc.in
Removed pkg config files for ilmClient from previous pull request.
Added initial pkg-config files / templates (.pc.in) for all shared libraries in wayland-ivi-extension
Adjusted cmake files to generate pkg-config files (.pc) from templates (.pc.in)
=> Add pkg config files v2

ivi-layermanagement-examples/EGLWLMockNavigation/src/OpenGLES2App.cpp
Before the application tried to register as xdg- and ivi-shell application. Now it only tries to register for one.
Signed-off-by: Michael Teyfel <mteyfel@de.adit-jv.com>
=> MockNavi: fixed selection between xdg- and ivi-shell

weston-ivi-shell/src/ivi-share.c
when the surface has touch-focus on the local screen
and you touch on the remote screen for some reason it can't
find the resource for the client. it will run off the endi
of the list and target_resource will be an invalid pointer.
=> Fix crash when surface already focused

CMakeLists.txt
This release includes following changes:
- add pkg-config files for ilmInput, ilmControl and ilmCommon libraries
- update to work with weston 2.0 release
- deprecate ilmClient API's, ilm_surfaceGetPixelformat and orientation API's:
ilm_layerSetOrinetation, ilm_layerGetOrientation
ilm_surfaceSetOrinetation, ilm_surfaceGetOrinetation
- fixed memory leaks and memory corruption in ilmControl
=> Bump to ilm to 1.13.0 stable version

ivi-layermanagement-api/ilmControl/src/ilm_control_wayland_platform.c
For the screen-id related commands such as "LayermanagerControl dump", the
command is failing since the screen-id is not properly updated. So ensuring
to get the screen-ids by doing a roundtrip.
Signed-off-by: Maniraj Devadoss <external.mdevadoss@de.adit-jv.com>
=> ilmControl:Added roundtrip to get screen-ids

ivi-layermanagement-examples/EGLWLInputEventExample/CMakeLists.txt, ivi-layermanagement-examples/EGLWLInputEventExample/include/WLContext.h, ivi-layermanagement-examples/EGLWLInputEventExample/src/WLContext.cpp, ivi-layermanagement-examples/EGLWLInputEventExample/src/WLEyesRenderer.cpp
Added support for cursor pointer image in EGLWLInputEventExample. If a mouse is attached a basic cursor pointer is loaded and shown on the application after clicking it. This approach is as minimal as possible.
=> Added support for cursor pointer image in EGLWLInputEventExample

ivi-layermanagement-api/ilmCommon/include/ilm_types.h, ivi-layermanagement-api/ilmControl/src/ilm_control_wayland_platform.c, ivi-layermanagement-examples/LayerManagerControl/src/print.cpp, protocol/ivi-wm.xml, weston-ivi-shell/src/ivi-controller.c
With this Pull request, we are sending connector name of a ivi screen, e,g,: HDMI-A-1, LVDS1.
@eucan updated LayerManagerControl, so that we can see this information there too.
=> Send screen connector name

ivi-layermanagement-examples/layer-add-surfaces/src/layer-add-surfaces.c
First patch implements  adding a layer to pregiven display. Displays are specified with their connector names.
Second patch ensures that layer-add-surfaces exits cleanly if ilm_init fails. ilm_init can fail for example if weston is not running.
=> Improve layer add surfaces

ivi-input-modules/ivi-input-controller/src/ivi-input-controller.c, weston-ivi-shell/src/ivi-controller.c, weston-ivi-shell/src/ivi-controller.h
This PR is a preparation for xdg-shell support in ivi-shell in the future. ivi-input-controller is not registering for surface signals of ivi-layout anymore but for new surface signals introduced in ivi-controller. Therefore ivi-input-controller is now dependent on ivi-controller. Moreover ivi-input-controller now uses ivisurface and ivishell instead of dedicated structs, that just copies meta data.
=> Make ivi-input-controller dependent on ivi-controller

protocol/CMakeLists.txt
so that it can be used by other components to
generate ivi-application-protocol.c and
ivi-application-client-protocol.h.
=> protocol: install ivi-application.xml in sysroot

ivi-input-modules/ivi-input-controller/src/ivi-input-controller.c
This fix removes a segmentation fault in weston for empty views without an attached buffer.
=> ivi-input-controller: fix for set_focus for empty view

ivi-layermanagement-examples/EGLWLInputEventExample/src/WLEyesRenderer.cpp
Bugfix: Formely a NULL pointer was given to wl_pointer_set_cursor although it was expecting the serial variable / an integer value.
=> WLEyesRenderer: resolved warning for wl_pointer_set_cursor during compilation

ivi-layermanagement-api/test/CMakeLists.txt, ivi-layermanagement-api/test/TestBase.cpp, ivi-layermanagement-api/test/TestBase.h, ivi-layermanagement-api/test/ilm_control_test.cpp
This PR:
- activates address sanitizer for unit tests
- Moves ivi-surface creation from testcases to SetUp() to avoid memory leaks in failing test-cases.
- Creates shared memory buffers and attaches to the surfaces
- Modifies SurfaceScreenshot test to except ILM_FAILED when it is called for not existing surface.
- Removes unnecessary sleep() in screenshot APIs.
Now every testcase is passing
=> Unit test improvements v1

ivi-layermanagement-examples/simple-ivi-share/src/simple-ivi-share.c, weston-ivi-shell/src/ivi-share.c
Currently, simple-ivi-share cannot update share surface in case that the client such as simple-egl is killed and restarted. Therefore, this case should be considered because it is possible some applications actually could be killed and restarted by user or system problem.
In current implementation, simple-ivi-share does not call get_share_surface() any more when the client is killed, so memory leak does not occur. But, during implementation of  this feature, I found that the memory leak could be happened when getting a share surface if the original surface does not exist.
When the original surface does not exist, ivi-share creates an empty nativesurface and sets the state of share surface as not exist. This empty nativesurface is still exist in memory, so memory leak could be occured. …
=> Update share surface when client restarts

ivi-layermanagement-examples/EGLWLMockNavigation/src/OpenGLES2App.cpp
MockNavi calls wl_surface_frame. However, it does not dispatch any default queue events.
Therefore, frame_listerner_func is never called and callback memory is leaked.
Originally, wl_surface_frame call is not needed and delete it.
Signed-off-by: Kenji Hosokawa <khosokawa@de.adit-jv.com>
=> EGLWLMockNavigation: fix memory leak

ivi-layermanagement-examples/EGLWLMockNavigation/include/OpenGLES2App.h, ivi-layermanagement-examples/EGLWLMockNavigation/src/OpenGLES2App.cpp, ivi-layermanagement-examples/EGLWLMockNavigation/src/main.cpp
This option used for eglSwapInterval API. Default value is 1. This means rendering is synced with frame callback.
When it is set to 0, EGLWLMockNavigation will not sync with frame callback and render it independently.
Signed-off-by: Kenji Hosokawa <khosokawa@de.adit-jv.com>
=> EGLWLMockNavigation: introduce sync option

ivi-layermanagement-api/ilmControl/src/ilm_control_wayland_platform.c
Change-Id: Ibf895036223cbbac03d614d6552f3a146f587f05
Signed-off-by: Romain Forlot <romain.forlot@iot.bzh>
=> fix wrong fprintf usage

ivi-input-modules/ivi-input-controller/src/ivi-input-controller.c
this option is removed from weston in 3.0
=> ivi-input: remove use_xkbcommon check

ivi-input-api/ilmInput/CMakeLists.txt, ivi-input-modules/ivi-input-controller/CMakeLists.txt, ivi-layermanagement-api/ilmClient/CMakeLists.txt, ivi-layermanagement-api/ilmCommon/CMakeLists.txt, ivi-layermanagement-api/ilmControl/CMakeLists.txt, ivi-layermanagement-examples/EGLWLInputEventExample/CMakeLists.txt, ivi-layermanagement-examples/EGLWLMockNavigation/CMakeLists.txt, ivi-layermanagement-examples/multi-touch-viewer/CMakeLists.txt, ivi-layermanagement-examples/simple-ivi-share/CMakeLists.txt, ivi-layermanagement-examples/simple-weston-client/CMakeLists.txt, protocol/CMakeLists.txt, weston-ivi-shell/CMakeLists.txt
Currently, all wayland protocol files are generated once in protocol folder and compiled to a static library, which is called libivi-extension-protocol.a. Then, this static library is linked to the every library which uses wayland protocol files.  But these libraries are using actually not all of the protocol files, which are linked into ivi-extension-protocol. Therefore, size of libraries increases unnecessarily.
I removed this static library. Now every library generates wayland protocol files with wayland-scanner. Only needed protocol files are linked into the binaries.
=> Remove ivi extension static library

weston-ivi-shell/src/ivi-share.c
This bug should be fixed for introducing the release_shared_name request.
=> ivi-share: fix wrong argument of alloc_share_nativesurface function

weston-ivi-shell/src/ivi-share-gbm.c, weston-ivi-shell/src/ivi-share.c, weston-ivi-shell/src/ivi-share.h
These patches are preparations for introducing the release_shared_name request.
It has been changed based on these patches.
=> Clean ivi share

protocol/CMakeLists.txt
Normally, wayland applications should generate wayland files from xml file via wayland-scanner.
In preparation for the case which the scanner can not be used, ivi-share.so is created. (e.g. 3rd party application)
Signed-off-by: Kenji Hosokawa <khosokawa@de.adit-jv.com>
=> ivi-share: create ivi-share.so

weston-ivi-shell/CMakeLists.txt
If IVI_SHARE is not defined, it is not necessary to generate it.
Signed-off-by: Kenji Hosokawa <khosokawa@de.adit-jv.com>
=> weston-ivi-shell: moving ivi-share-protocol creation

ivi-layermanagement-examples/simple-ivi-share/src/simple-ivi-share.c, protocol/ivi-share.xml, weston-ivi-shell/src/ivi-share.c, weston-ivi-shell/src/ivi-share.h
The compositor was unable to know whether shared buffers no longer needed.
Therefore, in spite of the consumer still using the buffer, the compositor was releasing the buffer to the producer.
In order to solve this problem, the request is introduced.
=>  ivi-share: introduce release_shared_name request

protocol/CMakeLists.txt
Creating doc files for protocols is not adding
any value. It is much easier to read xml file.
=> protocol: don't generate doc files for protocols

weston-ivi-shell/src/ivi-share.c
otherwise weston might randomly fail to init the module
=> ivi-share: add missing return value in setup_buffer_sharing()

ivi-layermanagement-examples/EGLWLInputEventExample/include/WLEyesRenderer.h, ivi-layermanagement-examples/EGLWLInputEventExample/src/WLEyesRenderer.cpp, ivi-layermanagement-examples/EGLWLInputEventExample/src/main.cpp
there is nothing to do if a wayland error occurs
we should just close the application
=> EGLWLInputEventExample: exit when wayland error occurs

ivi-input-modules/ivi-input-controller/src/ivi-input-controller.c
The w_view is not assigned with the local variable in input_ctrl_ptr_set_west_focus api.
Signed-off-by: Karthiraman Ramaiah <karthiraman.ramaiah@in.bosch.com>
=> ivi-input: update weston view for sending pointer coordinates

ivi-layermanagement-examples/layer-add-surfaces/src/layer-add-surfaces.c
ILM would only send notifications for the changes, which
are done AFTER ilm_surfaceAddNotification call.
If a surface configured between ilm_getPropertiesOfSurface
and ilm_surfaceAddNotification calls, we will never get
a configured event.
To fix this race condition, call ilm_surfaceAddNotification
first.
=> layer-add-surface: fix race condition of configure event

ivi-input-modules/ivi-input-controller/src/ivi-input-controller.c
Pointer focus is stored as surface_id integer, and it is not unset when surface is destroyed. I modified to code to unset pointer focus and store it as pointer of ivisurface. I simplified code a little bit by passing ivisurface pointers instead of surface_ids. Because it is easier to get ivi_layout_surface, seat_ctx or input_context from the ivisurface.
=> Unset pointer focus when surface is destroyed

ivi-input-modules/ivi-input-controller/src/ivi-input-controller.c
When a seat is destroyed remove the seat acceptance entry from surfaces which accept input events from this seat.
It is necessary that HMI controller monitors seat creation and  destruction events, for setting seat acceptance and input focus.
=> ivi-input: remove seat acceptance from surface when seat is destroyed

ivi-input-modules/ivi-input-controller/src/ivi-input-controller.c
- Remove unnecessary input_controller struct
- Remove duplicated while loop
- Don't store seat names in seat_ctx and seat_focus struct
=> Simplify ivi input implementation

ivi-layermanagement-api/ilmCommon/CMakeLists.txt, ivi-layermanagement-api/ilmCommon/ilmCommon.pc.in, ivi-layermanagement-api/ilmControl/CMakeLists.txt, ivi-layermanagement-api/ilmControl/ilmControl.pc.in, ivi-layermanagement-examples/LayerManagerControl/CMakeLists.txt, ivi-layermanagement-examples/layer-add-surfaces/CMakeLists.txt
Currently, ilmControl depends on ilmCommon. However, it is
ilmCommon that should depend on ilmControl.
Functions ilmControl_init and ilmControl_destroy are defined in
ilmControl, but are getting called from ilmCommon. Hence, ilmCommon
won't work without having ilmControl on the system at runtime. If
not found, there will be a runtime error which could be avoided
by linking these libraries correctly at build time.
Moreover, there is only a build time dependency of include headers
of ilmCommon on ilmControl. So at runtime, even if ilmCommon is not
present on the system, ilmControl can function independently.
This change corrects the dependency order of ilmCommon and
ilmControl.
Signed-off-by: Ashutosh Agarwal <asagarwal@nvidia.com>
Reviewed-by: Miguel Vico Moya <mvicomoya@nvidia.com>
=> wayland-ivi-extension: Correct the dependency order

ivi-layermanagement-examples/simple-weston-client/CMakeLists.txt, ivi-layermanagement-examples/simple-weston-client/src/simple-weston-client.c, weston-ivi-shell/src/ivi-controller.c, weston-ivi-shell/src/ivi-controller.h
These patches are related to weston-debug feature and dlt addition in weston-helper client.
PFB the details of changes made:
1) Based on the libweston-6-protocols pkgconfig file availability, decide whether to have the debug-protocol support or not.
2) Added new config option for debug-scopes. User desired debug-scopes are read from weston-ini and exported to weston-client through thorugh ivi-controller.
3) Route the weston logs to dlt. Weston will write to stdout through weston-debug protocol
and the dlt_ctx_thread will read from stdin
=>  Weston debug support

ivi-layermanagement-examples/simple-weston-client/src/simple-weston-client.c, weston-ivi-shell/src/ivi-controller.c, weston-ivi-shell/src/ivi-controller.h
By default the cursor wont be created, If the user wants then the "enable-cursor" option can be added as true in the ivi-shell section of weston config file, as shown below:
[ivi-shell]
...
enable-cursor=true
=> Make cursor creation optional

CMakeLists.txt
CMAKE_INSTALL_LIBDIR (at least) is used, so GNUInstallDirs needs
to be included. Otherwise it might expand to empty.
=> cmake: add missing include of GNUInstallDirs

weston-ivi-shell/src/ivi-controller.c, weston-ivi-shell/src/ivi-controller.h
A segmentation fault is observed on compositor de-init, if the simple-weston-client is already killed.
Here in termination sequence set_bkgnd_surface_prop function is called without active simple-weston-client resulting in segfault.
set_bkgnd_surface_prop function should be called only when the client is active.
=> Fix segmentation fault observed at compositor termination

ivi-layermanagement-api/ilmCommon/src/ilm_common.c
Segmentation fault is observed when ilm_isInitialized is called and if ilm_init was not called before. Here gIlmComonPlatformFunc is initialized in ilm_init using init_ilmCommonPlatformTable, so without calling ilm_init, gIlmCommonPlatformFunc.isInitialized is NULL. Hence calling ilm_isInitialized results in segfault.
Check whether gIlmComonPlatformFunc is initialized. ilm_isInitialized should be called only when gIlmComonPlatformFunc is initialized.
Signed-off-by: Shivakumar Halagatti <Shivakumar.Halagatti@in.bosch.com>
=> ilmCommon: Fix segmentation fault when ilm_isInitialized is called before ilm_init

ivi-layermanagement-api/ilmControl/CMakeLists.txt, ivi-layermanagement-api/ilmControl/src/bitmap.c, ivi-layermanagement-api/ilmControl/src/bitmap.h, ivi-layermanagement-api/ilmControl/src/ilm_control_wayland_platform.c, ivi-layermanagement-api/ilmControl/src/writepng.c, ivi-layermanagement-api/ilmControl/src/writepng.h
To save as png file, the file name should have ".png" as extension.
Signed-off-by: Ramzi BEN MEFTAH <rbmeftah@de.adit-jv.com>
=> ilmControl: add support for saving screenshot as png file

weston-ivi-shell/src/ivi-controller.c
The opaque region of a weston view is updated only if the alpha value is 1
and the transform matrix is of type WESTON_MATRIX_TRANSFORM_TRANSLATE.
Here opaque region is never updated, as we are performing scaling operations
to the view transform matrix(even when the scaling factor is 1), thus
changing the matrix type to WESTON_MATRIX_TRANSFORM_SCALE.
As a result, views are never opaque and won't be able to place it in
HW planes(forced to use renderer).
Perform scaling of the view transformation matrix only when the scaling
factor is non-zero.
=> Avoid unnecessary scaling of the view transformation matrix

ivi-layermanagement-api/ilmCommon/include/ilm_common.h, ivi-layermanagement-api/ilmCommon/include/ilm_types.h, ivi-layermanagement-api/ilmCommon/src/ilm_common.c, ivi-layermanagement-api/ilmControl/include/ilm_control_platform.h, ivi-layermanagement-api/ilmControl/src/ilm_control_wayland_platform.c, ivi-layermanagement-examples/layer-add-surfaces/src/layer-add-surfaces.c
We should gracefully exit when we encounter some unrecoverable errors in ilmControl, e.g.: OOM or wayland errors.
But before we exit, we have to send a notification to the application side that we are shutting down and releasing all resources.
=> Implement a shutdown notification for ilm

ivi-layermanagement-api/test/ilm_input_test.cpp, ivi-layermanagement-examples/EGLWLMockNavigation/src/TextureLoader.cpp, ivi-layermanagement-examples/simple-weston-client/src/simple-weston-client.c, weston-ivi-shell/src/ivi-controller.h
Solve compiler warnings for unused variable, return type of functions and indentation warnings.
=> Fix compiler warnings

ivi-input-modules/ivi-input-controller/src/ivi-input-controller.c
The seat destroy callback is triggered from weston_seat_release(),
that means the only way the code can enter destroy_seat() is with
all input devices associted with seat already released and all the
pointers already invalid. Avoid touching any of these input device
pointers in the destroy_seat() callback, otherwise this triggers
use-after-free condition.
ASan detects the use-after-free condition as follows:
```
==89420==ERROR: AddressSanitizer: heap-use-after-free on address 0x61100028e6a0 at pc 0x7f50deacb6fd bp 0x7ffed8504fe0 sp 0x7ffed8504fd8
WRITE of size 8 at 0x61100028e6a0 thread T0
#0 0x7f50deacb6fc in weston_keyboard_end_grab ../libweston/input.c:1604
#1 0x7f50bc6aac97 in destroy_seat (/tmp/wt/lib/x86_64-linux-gnu/weston/ivi-input-controller.so+0x7c97)
#2 0x7f50bc6ab02f in …
```
=> ivi-input-controller: Prevent use-after-free when tearing down seat

ivi-layermanagement-examples/simple-weston-client/CMakeLists.txt, ivi-layermanagement-examples/simple-weston-client/src/simple-weston-client.c
dlt should be optional in the simple-weston-client and a few other adaptations
=> Make dlt optional

ivi-layermanagement-examples/EGLWLInputEventExample/src/WLContext.cpp, ivi-layermanagement-examples/simple-weston-client/src/simple-weston-client.c
Fix array out of bounds access detected by gcc format fortification check:
```
In file included from /test/recipe-sysroot/usr/include/stdio.h:867,
from /test/git/ivi-layermanagement-examples/simple-weston-client/src/simple-weston-client.c:23:
In function 'fprintf',
inlined from 'create_cursors' at /test/git/ivi-layermanagement-examples/simple-weston-client/src/simple-weston-client.c:120:9,
inlined from 'seat_handle_capabilities' at /test/git/ivi-layermanagement-examples/simple-weston-client/src/simple-weston-client.c:247:9:
/test/recipe-sysroot/usr/include/bits/stdio2.h:100:10: error: '%s' directive argument is null [-Werror=format-overflow=]
100 |   return __fprintf_chk (__stream, __USE_FORTIFY_LEVEL - 1, __fmt,
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
101 | …
```
=> simple-weston-client: Repair array out of bounds access

ivi-layermanagement-examples/simple-weston-client/src/simple-weston-client.c
wlcontext->debug_iface didn't bind when weston has been running with non debug option. So, we need to check it before call weston_debug_v1_destroy.
Need to remove the while loop after send SIGINT, the stream->ojb always availbe in this case, then it makes a hang here.
=> simple-weston-client: fix crash and hang when exiting

ivi-layermanagement-api/ilmClient/include/ilm_client_platform.h, ivi-layermanagement-api/ilmClient/src/ilm_client_wayland_platform.c, ivi-layermanagement-api/ilmCommon/include/ilm_common_platform.h, ivi-layermanagement-api/ilmCommon/src/ilm_common_wayland_platform.c
fixes following error with the gcc 11.2.0:
usr/bin/ld: CMakeFiles/ilmCommon.dir/src/ilm_common_wayland_platform.c.o:(.bss+0x0): multiple definition of `gIlmCommonPlatformFunc'; CMakeFiles/ilmCommon.dir/src/ilm_common.c.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [ivi-layermanagement-api/ilmCommon/CMakeFiles/ilmCommon.dir/build.make:119: ivi-layermanagement-api/ilmCommon/libilmCommon.so.2.2.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:511: ivi-layermanagement-api/ilmCommon/CMakeFiles/ilmCommon.dir/all] Error 2
ilm_client and ilm_common both has the same issue.
fix: move the declaration to the c file and define the variable as "external"
in the header file
Signed-off-by: Jeka Friedrich <friedrix@gmail.com>
=> remove declaration of a global variable in a header file

protocol/CMakeLists.txt
ivi-application library uses wayland-client library symbol:
```
aarch64-linux-gnu-objdump -TC libivi-application.so | grep wl_
0000000000000000      D  *UND*	0000000000000000              wl_surface_interface
```
but couldn't observe it in the library's 'Dynamic Section':
```
aarch64-linux-gnu-objdump -p libivi-application.so | grep NEEDED
NEEDED               libc.so.6
```
Link libivi-application.so with libwayland-client.so to prevent undefined symbol errors.
=> protocol: Link ivi-application library with wayland-client library

ivi-layermanagement-examples/EGLWLInputEventExample/src/WLContext.cpp
We allocate the wl_cursor in the first step create_cursor, then tried to get the cursor object from wayland and override it. If wayland return a valid cursor, then when app exit, app and wayland tried to free it and we get the double free here.
Remove the allocation and free on the example to avoid double free.
=> EGLWLInputEventExample: fix crash when exit

ivi-layermanagement-examples/multi-touch-viewer/include/window.h, ivi-layermanagement-examples/multi-touch-viewer/src/multi-touch-viewer.c, ivi-layermanagement-examples/multi-touch-viewer/src/window.c
only a wl_shell or ivi surface is created base on wl_surface. we should select of the type of surface via input argument.
-s optional is added to example, if the input is 1, client will run with wl_shell. if option don't set or other value, the ivi surface is set.
=> multi-touch-viewer: add the surface selection optional

README
On Ubuntu 22.04, the display controller are using the wayland protocols by default. Run a new weston process need to pass the wayland display socket listening. Clients want to run with new weston process need to set WAYLAND_DISPLAY environment variable.
=> README: update for wayland backend

ivi-id-agent-modules/ivi-id-agent/src/ivi-id-agent.c
The WESTON_INCLUDE_DIRS contains a link to ${install_dir}/include/weston. So, header files should not include the weston directory in the path.
Signed-off-by: Tran Ba Khang(MS/EMC31-XC) <Khang.TranBa@vn.bosch.com>
=> ivi-id-agent: Revert the weston header link

ivi-input-modules/ivi-input-controller/src/ivi-input-controller.c, weston-ivi-shell/src/ivi-controller.c
Both ivi-controller and ivi-input-controller access functions which are
internal to weston, which means the ABI of these functions may change or
they may even be completely removed. So far, this wayland-ivi-extension
was able to link against libweston and use those functions by sheer luck,
but that may eventually run out. Copy over the internal functions as of
weston commit 2c1ed289 ("build: bump to version 9.0.92 for the beta release")
=> ivi-input-controller: ivi-controller: Copy over weston internal functions

ivi-layermanagement-api/ilmControl/src/ilm_control_wayland_platform.c
In function input_listener_input_acceptance, variable "surface_found" should be initialized to 0.
Only then "if(!surface_found)" will take effect.
Signed-off-by: Au Doan Ngoc <au.doanngoc@vn.bosch.com>
=> IlmControl: Fix no warning when passing an invalid surface to function input_listener_input_acceptance

ivi-id-agent-modules/ivi-id-agent/CMakeLists.txt, ivi-layermanagement-examples/simple-weston-client/CMakeLists.txt
Update the libweston-9 on ivi-id-agent cmake file. Update the libweston-9-protocols on simple-weston-client cmake file.
Signed-off-by: Tran Ba Khang(MS/EMC31-XC) <Khang.TranBa@vn.bosch.com>
=> Weston 9 compatible

ivi-layermanagement-examples/simple-weston-client/src/simple-weston-client.c
Currently signal handling is not properly done while listening for events on wayland socket. As a result process waits on poll() for idefinite time even after receiving signal.
Modify poll() to accept signals while listening to events on wayland socket.
Signed-off-by: Rajendraprasad K J <KarammelJayakumar.Rajendraprasad@in.bosch.com>
=> simple-weston-client: Improve signal handling

weston-ivi-shell/src/ivi-controller.c
In function controller_screen_get, iviscrn should be checked for null before assigning it to a pointer.
If it is assigned before the check condition, the condition becomes meaningless.
Signed-off-by: Au Doan Ngoc <au.doanngoc@vn.bosch.com>
=> ivi-controller: Fix the problem of assigning an address to a pointer

weston-ivi-shell/src/ivi-controller.c, weston-ivi-shell/src/ivi-controller.h
From weston version 8.0.0, data type of param in
weston_config_section_get_bool() changed from int to bool. So, we need to update in wayland-ivi-extension source.
(< version 8.0.0 )
(>= version 8.0.0)
=> ivi-controller: update data type of member in struct ivishell

ivi-layermanagement-api/test/CMakeLists.txt, ivi-layermanagement-api/test/ilm_check_env.cpp
The environment checking test verifies the versions of ivi_wm and ivi_input from compositor. It makes sure the server is providing the client's expectation versions.
It also tries to bind the protocols via registry.
=> tests: add the ilm env checking test

ivi-layermanagement-examples/simple-weston-client/src/simple-weston-client.c, weston-ivi-shell/src/ivi-controller.c
The weston_surface_set_color should be only called to setup the color of a surface without a buffer attached (BUFFER_TYPE_SOLID). Currently, ivi-controller is used it to setting the color of a background surface with type of buffer is SHM.
On weston 10, with commit [1], it don't allow to re-draw a surface if getting an unexpected of shader properties, we will get an assertion.
On weston 11, with the commit [2], weston will remove the weston_surface_set_color api, we can't use it any more.
On hmi-controller and desktop-shell, filling the image or color of the backgound is done by client. Just follow this way in ivi-controller.
[1] https://gitlab.freedesktop.org/wayland/weston/-/commit/0f52da62
[2] https://gitlab.freedesktop.org/wayland/weston/-/commit/b5605ccd
=> ivi-controller: set surface background color from client side

ivi-layermanagement-examples/simple-weston-client/src/simple-weston-client.c
The signalfd() maybe 0 when this app is loaded by Weston (setup ivi-client-name in weston.ini). The fd same with STDIN_FILENO, if anything write to STDIN, the signal handler will be occured unexpectedly.
Using the define fd from pipe() to avoid the issue.
=> simple-weston-client.c: avoid to use STDOUT_FILENO and STDIN_FILENO

CMakeLists.txt
2.3.0 version
this commit will be the last compatible version with weston 9
new api's:
ilm_getDefaultSeat
get the name of default seat
ilm_takeAsyncScreenshot
ilm_takeAsyncSurfaceScreenshot
both api's provides a way to get the screenshot of the screen or particular surface in asynchronous manner, user will be notified via callback
other updates:
Tran Ba Khang:
simple-weston-client.c: avoid to use STDOUT_FILENO and STDIN_FILENO
ivi-controller: set surface background color from client side
ilm_input_test: update tests with default seat
ilmInput: support ilm_getDefaultSeat api to return default seat name
ivi-input-modules: read default seat name from weston.ini file
tests: add the ilm env checking test
CMakeLists: update libweston to version 9
tests: create tests for new screenshot functions …
=> bump 2.3.0 version

ivi-id-agent-modules/ivi-id-agent/CMakeLists.txt, ivi-layermanagement-examples/simple-weston-client/CMakeLists.txt
CMakeLists: update libweston to version 10
Update the libweston-10 on ivi-id-agent cmake file.
Update the libweston-10-protocols on simple-weston-client cmake file
=> Weston 10 compatible

ivi-id-agent-modules/ivi-id-agent/CMakeLists.txt, ivi-input-modules/ivi-input-controller/CMakeLists.txt, weston-ivi-shell/CMakeLists.txt
If weston built with meson version 0.62 or higher, the weston.pc file will not generate the libdir variable. wayland-ivi-extension base on this to find the weston modules plugin directory.
Switch to base on libdir variable of libweston.pc for get our purpose.
=> CMakeLists.txt: fix build failed with newer version of meson

weston-ivi-shell/src/ivi-controller.c
ivi-controller: fix wrong pointer in output_resized event
=> ivi-controller: fix wrong pointer in output_resized event

CMakeLists.txt, ivi-id-agent-modules/ivi-id-agent/CMakeLists.txt, ivi-input-modules/ivi-input-controller/CMakeLists.txt, ivi-layermanagement-examples/simple-weston-client/CMakeLists.txt, weston-ivi-shell/CMakeLists.txt
CMakeLists: update libweston to version 11
Update the libweston-11 on ivi-id-agent cmake file.
Update the libweston-11-protocols on simple-weston-client cmake file
=> Weston 11 compatible

ivi-id-agent-modules/ivi-id-agent/CMakeLists.txt, ivi-id-agent-modules/ivi-id-agent/src/ivi-id-agent.c, weston-ivi-shell/CMakeLists.txt, weston-ivi-shell/src/ivi-controller.c, weston-ivi-shell/src/ivi-controller.h
On weston 11, with the commit [1], the ivi-layout emits the surface create event for desktop surface is earlier.
This make the sequence issue when id-agent hasn't already setup the surface id for desktop surface, but the ivi-controller is going to send the surface create event to client with INVALID id.
[1] https://gitlab.freedesktop.org/wayland/weston/-/commit/924e79f4f
=> ivi-controller: support to setting desktop surface id earlier

ivi-layermanagement-api/ilmControl/include/ilm_control_platform.h, ivi-layermanagement-api/ilmControl/src/ilm_control_wayland_platform.c, ivi-layermanagement-api/test/ilm_check_env.cpp, ivi-layermanagement-api/test/ilm_control_notification_test.cpp, protocol/ivi-wm.xml, weston-ivi-shell/src/ivi-controller.c
On weston 11, with commit [1], the weston_renderer is no longer access from outside, it becomes to private. The ivi-controller is using the read_pixels of that structure for the screen shoot feature.
To continue to support the screen shoot, we need to switch to the new mechanism. Using the weston_screenshooter_shoot api is the best solution. With this api, ilm client needs to prepare a shm buffer, then send it to the ivi-controller.
This change will affect to ivi_screenshot, ivi_wm_screen, and ivi_wm interfaces.
[1] https://gitlab.freedesktop.org/wayland/weston/-/commit/0c65b2384
=> ivi-controller: new mechanism for screenshot

weston-ivi-shell/src/ivi-controller.c
Weston 11 commit [1] don't allow to paint the views if it or its surface didn't map. So, need to call weston_surface_map and set the map of view to true.
[1] https://gitlab.freedesktop.org/wayland/weston/-/commit/f962b4895
=> ivi-controller: mapping bkgnd surface and view before repain

ivi-layermanagement-api/ilmClient/src/ilm_client_wayland_platform.c, ivi-layermanagement-api/ilmControl/src/ilm_control_wayland_platform.c, ivi-layermanagement-api/test/TestBase.cpp, ivi-layermanagement-api/test/ilm_check_env.cpp, ivi-layermanagement-examples/EGLWLInputEventExample/include/WLEyesRenderer.h, ivi-layermanagement-examples/EGLWLInputEventExample/src/WLContext.cpp, ivi-layermanagement-examples/EGLWLInputEventExample/src/WLEyesRenderer.cpp, ivi-layermanagement-examples/EGLWLInputEventExample/src/main.cpp, ivi-layermanagement-examples/EGLWLMockNavigation/src/House.cpp, ivi-layermanagement-examples/EGLWLMockNavigation/src/OpenGLES2App.cpp, ivi-layermanagement-examples/multi-touch-viewer/src/multi-touch-viewer.c, ivi-layermanagement-examples/multi-touch-viewer/src/window.c, ivi-layermanagement-examples/simple-weston-client/src/simple-weston-client.c
[  1%] Generating ivi-application-protocol.c
Using "code" is deprecated - use private-code or public-code.
See the help page for details.
[  2%] Generating ivi-application-client-protocol.h
[  3%] Building C object protocol/CMakeFiles/ivi-application.dir/ivi-application-protocol.c.o
[  4%] Linking C shared library libivi-application.so
[  4%] Built target ivi-application
[  5%] Generating ivi-wm-server-protocol.h
[  6%] Generating ivi-wm-protocol.c
Using "code" is deprecated - use private-code or public-code.
See the help page for details.
[  7%] Building C object weston-ivi-shell/CMakeFiles/ivi-controller.dir/src/ivi-controller.c.o
[  8%] Building C object weston-ivi-shell/CMakeFiles/ivi-controller.dir/ivi-wm-protocol.c.o
[  9%] Linking C shared module ivi-controller.so
[  9%] Built …
=> Fix build warning

ivi-input-modules/ivi-input-controller/src/ivi-input-controller.c
Controller needs to end grab all input devices before release a seat. This helps to avoid the use-after-free issue in weston [1].
We should't end grab input devives in seat_destroy event, because they already released [2].
[1] https://github.com/COVESA/wayland-ivi-extension/commit/5d410575
[2] https://github.com/COVESA/wayland-ivi-extension/commit/a5272996
=> ivi-input-controller: end grab of all devices when destroy a seat

ivi-layermanagement-api/ilmControl/src/ilm_control_wayland_platform.c, weston-ivi-shell/src/ivi-controller.c
Some variables has name which same with keyword (not).
Rename these varable to another name
=> Rename variables to avoid keywords

ivi-layermanagement-api/ilmControl/src/ilm_control_wayland_platform.c
fixes following warning from wayland library:
warning: queue 0x55ccae144a00 destroyed while proxies still attached:
ivi_input#7 still attached
to avoid the warning we should destroy
the input controller resources (proxies) before destroying the queue of ilm control
=> ilm_control: fix order during destroying of control resources

ivi-layermanagement-api/ilmInput/src/ilm_input.c
release_instance is called when no sync_and_acquire_instance is called before.
=> ilm_input: remove redunant release_instance

CMakeLists.txt, ivi-id-agent-modules/ivi-id-agent/CMakeLists.txt, ivi-id-agent-modules/ivi-id-agent/src/ivi-id-agent.c, weston-ivi-shell/CMakeLists.txt, weston-ivi-shell/src/ivi-controller.c
Commit [1] on Weston-12 moved libweston-desktop into libweston, then libweston-desktop.pc was deleted.
[1] https://gitlab.freedesktop.org/wayland/weston/-/commit/1b4def3c4
=> CMakefiles: remove libweston-desktop dependence

weston-ivi-shell/src/ivi-controller.c
Commit [1] on Weston-12 switched to use assert() to check input arguments, then some of APIs from ivi-layout were modified.
[1] https://gitlab.freedesktop.org/wayland/weston/-/commit/a3a843163
=> ivi-controller: adapt the changing from ivi-layout

weston-ivi-shell/CMakeLists.txt, weston-ivi-shell/src/config.h.cmake, weston-ivi-shell/src/ivi-controller.c
Commit [1] on Weston 12 removed the wet_load_module_entrypoint interface, this requires users switch to weston_load_module for loading other plugins.
[1] https://gitlab.freedesktop.org/wayland/weston/-/commit/eaf2de344
=> ivi-controller: switch to weston_load_module

weston-ivi-shell/src/ivi-controller.c
- set view.transform.dirty before repaint
- avoid to repaint view when destination is 0
=> ivi-controller: Update to repaint background

ivi-id-agent-modules/ivi-id-agent/src/ivi-id-agent.c, ivi-input-modules/ivi-input-controller/src/ivi-input-controller.c, weston-ivi-shell/src/ivi-controller.c
Merge request [1] on Weston-12 introduced new signal from ivi-shell. ivi-controller is depended on ivi-shell, so it should depend on ivi-shell instead of compositor when exiting.
[1] https://gitlab.freedesktop.org/wayland/weston/-/merge_requests/1043
=> ivi-controller: switch to ivi-shell terminal signal

weston-ivi-shell/src/ivi-controller.c
On set_bkgnd_surface_prop() API, 'bkgnd_transform.link' is removed from transformation list but it is not initialized, so it may lead to invalid mem access when set_bkgnd_surface_prop() is called again. So initialize the 'bkgnd_transform.link' after the removing it.
=> ivi-controller: avoid invalid mem access during display hotplug
